######################################################################
##
## Filename: PS2_RX_TB.udo
## Created on: Mon Mar 20 09:07:40 Środkowoeuropejski czas stand. 2017
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
